version: "3.8"

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
    network_mode: service:db
    command: sleep infinity

  db:
    container_name: classinet-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: classinet

volumes:
  postgres-data:
